
name: Python Test

on:
  push:  # Trigger workflow on push
    branches:
      - main  # Only run on the "main" branch
  pull_request:  # Trigger workflow on pull requests

jobs:
  test:
    runs-on: ubuntu-latest  # Use Ubuntu as the environment

    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # Check out repository code

      - name: Set up Python
        uses: actions/setup-python@v4  # Set up Python environment
        with:
          python-version: '3.10'  # Specify Python version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Install dependencies

      - name: Run tests
        run: |
          pytest  # Run pytest for testing
